### ISSUE TITLE
gitches disappeared

### ISSUE THREAD

**Issue by reimersjan** [bullgit/map#2]
i see no more gitches on the map. tested in firefox and chrome. i have no clue why

EDIT: i get this error in the console
`SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 11 column 7 of the JSON data` in `map.js:24:14`

**Comment by Haroenv** [comment]
fixed https://github.com/bullgit/bullgit.github.io/commit/bb5781b9b1ba98d38c34d2ac5948ac699dc5245a
